### PR TITLE
Allow + operator on email address

### PR DESCRIPTION
**Pull request by thiagoaugusto**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://thiagoaugusto-patch-4.ruby-jobs-ruby-jobs-7a915cad74d3818e1662.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://thiagoaugusto-patch-4.ruby-jobs-ruby-jobs-7a915cad74d3818e1662.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by matheusml** [comment]
@esasse @brunozrk ok?

**Comment by esasse** [comment]
Eu acho que deveria ter um teste.

**Comment by brunozrk** [comment]
:+1:

**Comment by esasse** [comment]
:+1:

**Comment by lccezinha** [comment]
:+1:

**Comment by matheusml** [comment]
\o/

**Pull request merged**
